arrowParens = "always"
bracketSpacing = true
insertPragma = false
jsxBracketSameLine = false
printWidth = 80
proseWrap = "always"
requirePragma = false
semi = true
singleQuote = false
tabWidth = 4
trailingComma = "all"

[[overrides]]
files = "*.ts"
[overrides.options]
printWidth = 120
tabWidth = 2

[[overrides]]
files = "*.js"
[overrides.options]
printWidth = 120
tabWidth = 2

[[overrides]]
files = "*.tsx"
[overrides.options]
printWidth = 120
tabWidth = 2

[[overrides]]
files = "*.jsx"
[overrides.options]
printWidth = 120
tabWidth = 2

[[overrides]]
files = ["*.json", "*.json5"]
[overrides.options]
printWidth = 120
tabWidth = 2

[[overrides]]
files = "*.md"
[overrides.options]
proseWrap = "never"
